from python:3.12-slim

WORKDIR /utility

COPY utility-python/ /utility/

RUN python -m venv venv


RUN venv/bin/pip install -r requirements.txt

RUN venv/bin/python -m unittest discover -s /utility-python/tests -p "test_*.py" -f

CMD ["venv/bin/python", "generate_log.py"]